version: 0.1.{build}
configuration: Release
platform: x86
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    7z a FiveTool.zip %APPVEYOR_BUILD_FOLDER%\FiveTool\bin\Release\*.exe %APPVEYOR_BUILD_FOLDER%\FiveTool\bin\Release\*.dll

    7z a ModuleExtractor.zip %APPVEYOR_BUILD_FOLDER%\Release\ModuleExtractor.exe
artifacts:
- path: FiveTool.zip
  name: FiveTool
- path: ModuleExtractor.zip
  name: ModuleExtractor